import os
from glob import glob
from pathlib import Path

import pandas as pd
import yaml
from linkml_runtime.linkml_model import SlotDefinition
from linkml_runtime.linkml_model.meta import SchemaDefinition
from linkml_runtime.utils.schema_as_dict import schema_as_dict
from schemasheets.schemamaker import SchemaMaker

from odm_linkmlgen.utils.general_utils import (
    EMPTY_PERMISSIBLE_VALUE,
    get_logger,
    order_columns,
    save_data_frame,
)

logger = get_logger(__name__)


def make_linkml_schema_from_schemasheets(
    schemasheets_dir: str | Path, output_schema: str | Path | None = None
) -> SchemaDefinition:
    """Create a LinkML schema from all the Schemasheets definition files in the
    specified directory.

    Args:
        schemasheets_dir (str | Path): The directory containing all the Schemasheets definition
            files. All .tsv files are used.
        output_schema (str | Path | None, optional): The YAML file to save the LinkML schema to.
            Defaults to None.

    Returns:
        SchemaDefinition: The generated schema.
    """
    logger.info(
        f"Making LinkML schema at '{output_schema}' from Schemasheets files in '{schemasheets_dir}'"
    )
    sm = SchemaMaker(
        use_attributes=False,
        unique_slots=False,
        gsheet_id=None,
        default_name=None,
        table_config_path=None,
    )
    input_sheets = glob(str(Path(schemasheets_dir) / "*.tsv"))
    schema = sm.create_schema(input_sheets)
    schema = sm.repair_schema(schema)
    fix_schemasheets_generated_schema(schema)

    if output_schema:
        save_schema_definition(schema, output_schema)

    return schema


def save_schema_definition(schema: SchemaDefinition, output_file: str | Path):
    """Save the schema to disk as a LinkML YAML schema file.

    Args:
        schema (SchemaDefinition): The SchemaDefinition to save to disk.
        output_file (str | Path): The YAML file to save to.
    """
    schema_dict = schema_as_dict(schema)

    if os.path.dirname(output_file):
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        f.write(yaml.dump(schema_dict, sort_keys=False))
    logger.info(f"LinkML schema saved to '{output_file}'")


def fix_schemasheets_generated_schema(schema: SchemaDefinition):
    """Do some fixing up of a Schemasheets-generated schema (generated by SchemaMaker). This is
    to account for errors or deficiencies in Schemasheets, and should hopefully in the long-term
    be eliminated. This includes:

    - Converting minimum_value and maximum_value for slots to numbers (Schemasheets makes them
    strings, which causes problems by downstream LinkML tools).
    - Replacing any permissible_value equal to EMPTY_PERMISSIBLE_VALUE with "". Schemasheets
    treats a blank permissible_value in a Schemasheets row as info for the top-level enum,
    rather than for a permissible value of the enum equal to "".

    Args:
        schema (SchemaDefinition): The schema
    """
    # Replace any permissible_value equal to EMPTY_PERMISSIBLE_VALUE to be blank.
    # Schemasheets uses a blank permissible_value to represent a row for the top-level
    # enum (ie. descriptions and titles associated with the enum) rather than a permissible
    # value of an enum. This makes it impossible to create a blank permissible value (eg.
    # for values representing not-applicable, NA, etc). To work around this, we've defined
    # an empty permissible value tag of EMPTY_PERMISSIBLE_VALUE that we replace with "" here.
    for enum_definition in schema.enums.values():
        if EMPTY_PERMISSIBLE_VALUE in enum_definition.permissible_values:
            enum_definition.permissible_values = {
                ("" if k == EMPTY_PERMISSIBLE_VALUE else k): v
                for k, v in enum_definition.permissible_values.items()
            }

    # Schemasheets improperly sets minimum_value and maximum_value as strings, which can cause
    # problems downstream such as with the LinkML validator. We convert them to floats or integers
    # here.
    def _make_number(key: str, slot_definition: SlotDefinition):
        """Convert one of the slot definition's values from a string to a number, in place.

        Integer-valued numbers are converted to int, everything else to float. A value that
        cannot be converted is set to None (and a warning is logged), and an NA value is
        left untouched.

        Args:
            key (str): The slot definition key to convert (eg. "minimum_value").
            slot_definition (SlotDefinition): The slot definition to modify in place.
        """
        val = slot_definition[key]
        if pd.isna(val):
            return
        try:
            float_val = float(val)
            val = int(float_val) if float_val == int(float_val) else float_val
        except (TypeError, ValueError):
            logger.warning(f"Unrecognized {key}: {val} of type {type(val)}, using None")
            val = None
        slot_definition[key] = val

    for class_definition in schema.classes.values():
        for slot_definition in class_definition.slot_usage.values():
            _make_number("minimum_value", slot_definition)
            _make_number("maximum_value", slot_definition)

    # For slots that have multiple ranges, change the range string into an array (eg.
    # If "range: sampleRelSet, protocolRelSet" then change it to "range: ['sampleRelSet', 'protocolRelSet']")
    for class_definition in schema.classes.values():
        for slot_definition in class_definition.slot_usage.values():
            if slot_definition.range and "," in slot_definition.range:
                slot_definition.range = [
                    s.strip() for s in slot_definition.range.split(",")
                ]


def save_schemasheet(
    data: dict | list | pd.DataFrame,
    file_name: str | Path,
    headers: list[str] | dict[str, str] | None = None,
) -> pd.DataFrame:
    """Create a Schemasheet file from the data. Schemasheets headers (with a row preceded by a '>') are also added
    according to headers. Headers are ordered according to the order in headers, with any header not found
    in headers placed at the end.

    Args:
        data (dict | list | pd.DataFrame): The data to save to the Schemasheet. If a dict or a list
            of dicts then the keys become the headers and the values are the rows.
        file_name (str | Path): The file to save the Schemasheet to.
        headers (list[str] | dict[str, str] | None, optional): If set and a dict then defines what Schemasheets header each header in the data
            maps to. If a list then specifies the order of the headers as well as the headers in the data that map to the a
            Schemasheet header of the same name. Any header in the data missing in headers is mapped to the Schemasheets header
            "ignore". Defaults to None.

    Returns:
        pd.DataFrame: The final Schemasheets DataFrame saved to disk. It includes the Schemasheets headers row, with the
            columns sorted according to the headers parameter.
    """
    # Create a Pandas DataFrame from the data
    if isinstance(data, pd.DataFrame):
        df = data
    elif isinstance(data, dict):
        if isinstance(data[next(iter(data))], (list, tuple)):
            index = None
        else:
            index = [0]
        df = pd.DataFrame(data, columns=data.keys(), index=index)
    else:
        df = pd.DataFrame(data, index=range(len(data)))

    if headers is None:
        headers = {k: k for k in df.columns}
    elif not isinstance(headers, dict):
        headers = {k: k for k in headers}

    # Order columns and add the Schemasheets headers
    df = order_columns(df, headers.keys())
    df = add_schemasheets_header(df, headers)

    save_data_frame(df, file_name, index=False)

    return df


def make_container_schemasheet(
    class_names: list[str],
    output_file: str | Path,
    class_titles: dict[str, str] | None = None,
) -> None:
    """Build and save the top-level Container class Schemasheet.

    Each class in class_names becomes a multivalued, inlined slot on the Container class.

    Args:
        class_names (list[str]): The names of the classes to include as slots.
        output_file (str | Path): The TSV file to save to.
        class_titles (dict[str, str] | None, optional): Mapping of class name to slot title.
            Missing or None entries produce an empty title string. Defaults to None.
    """
    import pandas as pd

    columns = [
        "class",
        "slot",
        "range",
        "tree_root",
        "multivalued",
        "inlined_as_list",
        "title",
        "description",
    ]
    rows = [{"class": "Container", "tree_root": True}]
    for class_name in class_names:
        rows.append(
            {
                "class": "Container",
                "slot": class_name,
                "range": class_name,
                "multivalued": True,
                "inlined_as_list": True,
                "title": (class_titles or {}).get(class_name, ""),
                "description": "",
            }
        )
    df = pd.DataFrame(rows)
    save_schemasheet(df, output_file, columns)


def add_schemasheets_header(df: pd.DataFrame, headers: dict) -> pd.DataFrame:
    """Insert Schemasheets header line. This is the line that starts with ">" and is
    inserted as the first row (immediately below the existing Pandas column names).

    Args:
        df (pd.DataFrame): The DataFrame to add the Schemasheets headers to.
        headers (dict): The Schemasheets headers to add. The keys are names for
            the existing df column names. The values are the Schemasheet
            headers to add in the matching column. Note that ">" will be added
            automatically to the first header. Any DataFrame column not found
            in this dictionary will receive the Schemasheet header "ignore".

    Returns:
        pd.DataFrame: The DataFrame with the new Schemasheet header as the first row.
            A copy of the DataFrame is made.
    """
    if len(df.columns) == 0 or len(df.index) == 0:
        raise ValueError(
            "DataFrame must not be empty in order to add a Schemasheets header"
        )
    df = df.copy().reset_index(drop=True)
    df.loc[-1] = [""] * len(df.columns)
    df.index = df.index + 1
    df = df.sort_index()
    for idx, col in enumerate(df.columns):
        new_header = headers.get(col, None) or "ignore"
        if idx == 0:
            new_header = f"> {new_header}"
        df.loc[0, col] = new_header
    return df
